inverted.exe: create.o display.o main.o save.o search.o update.o validate.o
	gcc -o inverted.exe create.o display.o main.o save.o search.o update.o validate.o
create.o:create.c
	gcc -c create.c
display.o:display.c
	gcc -c display.c
main.o:main.c
	gcc -c main.c
save.o:save.c
	gcc -c save.c
search.o:search.c
	gcc -c search.c
update.o:update.c
	gcc -c update.c
validate.o:validate.c+++
	gcc -c validate.c
clear:
	rm *.exe *.o